spring:
  config:
    activate:
      on-profile: test
  mail:
    host: #{spring.mail.host}
    port: #{spring.mail.port}
    properties:
      mail.smtp.ssl.enable: true
    username: #{spring.mail.username}
    password: #{spring.mail.password}
    to: #{spring.mail.to}
j-forex:
#  uri: https://platform.dukascopy.com/demo/jforex.jnlp
  uri: https://platform.dukascopy.com/demo_3/jforex_3.jnlp
  public-key: DEMO210037QdsWQEU
  private-key: QdsWQ
