server:
  port: 8080
  servlet:
    context-path: /forex
spring:
  application:
    name: forex
  mail:
    host: 0.0.0.0
logging:
  level:
    web: trace
push:
  stomp:
    broker: /topic
    endpoints:
      -
         point: /order
         allowed-origins: "*"
    stats-logging-period: 0
